services:

  web:
    image: 'thirimon/drivewise-web:3'
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    ports:
      - "8082:8080"
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect

