services:
#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    environment:
#      POSTGRES_DB: postgres
#      POSTGRES_USER: demouser2
#      POSTGRES_PASSWORD: Thiri123
#    ports:
#      - "5433:5432"
#    healthcheck:
#      test: ["CMD-SHELL", "pg_isready -U demouser2"]
#      interval: 10s
#      timeout: 5s
#      retries: 3

  web:
    image: 'thirimon/drivewise-web:3'
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    ports:
      - "8080:8080"
#    depends_on:
#      postgres:
#        condition: service_healthy
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
#      POSTGRES_HOST_AUTH_METHOD: trust
