name: Build and deploy container app to Azure Web App - thiriuniprojcd

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: thirimon/drivewise-web

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

        # Step 2: Set up Java JDK
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

        # Step 3: Build the JAR file
      - name: Build the application
        run: mvn clean package -DskipTests=true

        # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

        # Step 5: Build and push Docker image
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.run_number }} .

      - name: Push Docker image
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'thiriuniprojcd'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_fa53aa112f0641c4aff4fab2aed9fa54 }}
          images: ${{ env.IMAGE_NAME }}:${{ github.run_number }}
