# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - thiriuniprojcd

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: thirimon/drivewise-web

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

      # Step 2: Set up Java JDK
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '21'

      # Step 3: Build the JAR file
    - name: Build the application
      run: mvn clean package -DskipTests=true

      # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the Docker image
    - name: Build Docker image
      run: docker build -t thirimon/drivewise-web:${{ github.run_number }} .

      # Push the Docker image
    - name: Push Docker image
      run: docker push thirimon/drivewise-web:${{ github.run_number }}

#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v2
#
#    - name: Log in to registry
#      uses: docker/login-action@v2
#      with:
#        registry: https://index.docker.io/v1/
#        username: ${{ secrets.AzureAppService_ContainerUsername_c75b03715fad4e7ea778225afcb7b526 }}
#        password: ${{ secrets.AzureAppService_ContainerPassword_917c15399ce64037a0cf9adc9f370268 }}
#
#    - name: Build and push container image to registry
#      uses: docker/build-push-action@v3
#      with:
#        push: true
#        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c75b03715fad4e7ea778225afcb7b526 }}/thirimon/drivewise-web:${{ github.sha }}
#        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
#      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'thiriuniprojcd'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fa53aa112f0641c4aff4fab2aed9fa54 }}
        images: 'thirimon/drivewise-web:${{ github.run_number }}'
#        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_c75b03715fad4e7ea778225afcb7b526 }}/thirimon/drivewise-web:${{ github.run_number }}'
